### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by ccorcos** [raix/Meteor-famono#102]
how do you typically integrating routing (iron router) with famous? It seems you could entirely get rid of Blaze and templating...

**Comment by raix** [comment]
So on mobile apps I tend to think in States instead of routes - routes are handy for sharing references - but not for describing a state like modals etc.

famous uses scenes + eventemitters for this (you can easily build a state machine or even nest these)

There are some related patterns eg. Flux that couples in to stuff like this (inter/external component communication)

**Comment by ccorcos** [comment]
I see. So you don't use this for web?

**Comment by raix** [comment]
I dont use famous, it havent been ready for use (phones arent ready yet, api's are too unreliable), i'm considering it a pattern.
